<?php
/*
 * Authentication service operations.
 */

require_once __DIR__ . '/../../infrastructure/database/auth-repository.php';
require_once __DIR__ . '/../shared/transaction-retry.php';

/**
 * Authenticate a staff member by email or Staff_ID.
 *
 * @return array|null
 */
function authenticateStaff(PDO $pdo, $identifier, $password)
{
    if (!is_string($identifier) || !is_string($password)) {
        return null;
    }

    $user = findStaffForLogin($pdo, $identifier);

    if (!$user
        || !in_array($user['Role'] ?? null, ['Admin', 'Manager', 'Staff'], true)
        || !is_int($user['Auth_Revision'] ?? null)
        || $user['Auth_Revision'] < 1
        || !password_verify($password, $user['Password'])) {
        return null;
    }

    return [
        'staff_id' => $user['Staff_ID'],
        'full_name' => $user['Full_Name'],
        'email' => $user['Email'],
        'role' => $user['Role'],
        'auth_revision' => $user['Auth_Revision']
    ];
}

/**
 * Password-reset tokens are intentionally short-lived. No application
 * configuration currently defines a reset TTL, so the controlled lifecycle
 * uses a 30-minute default and accepts only a bounded 5- to 60-minute range.
 */
function getPasswordResetTokenTtlSeconds($requestedTtl = null)
{
    $defaultTtl = 1800;

    if ($requestedTtl === null) {
        return $defaultTtl;
    }

    if (!is_int($requestedTtl) || $requestedTtl < 300 || $requestedTtl > 3600) {
        throw new InvalidArgumentException('Invalid password reset token lifetime.');
    }

    return $requestedTtl;
}

/**
 * Validate a Staff_ID for an internal reset lifecycle call.
 */
function validatePasswordResetStaffId($staffId)
{
    if (!is_string($staffId)) {
        throw new InvalidArgumentException('Invalid password reset staff identifier.');
    }

    $staffId = trim($staffId);
    if ($staffId === ''
        || strlen($staffId) > 20
        || !preg_match('/^[A-Za-z0-9_-]+$/', $staffId)) {
        throw new InvalidArgumentException('Invalid password reset staff identifier.');
    }

    return $staffId;
}

/**
 * Validate the internal token format generated by issuePasswordResetToken().
 */
function validatePasswordResetRawToken($rawToken)
{
    return is_string($rawToken)
        && preg_match('/\A[0-9a-f]{64}\z/D', $rawToken) === 1;
}

/**
 * Validate the existing minimum password convention without emitting an API
 * response from the service layer.
 */
function isValidPasswordResetPassword($password)
{
    return is_string($password)
        && strlen($password) >= 6
        && strlen($password) <= 255;
}

/**
 * Execute a short password-reset transaction with the project's bounded
 * contention retry behavior. The caller always receives a closed transaction.
 */
function runAuthenticationRevisionTransaction(PDO $pdo, callable $operation)
{
    if ($pdo->inTransaction()) {
        throw new RuntimeException('Password reset transaction cannot be nested.');
    }

    $maxAttempts = 3;

    for ($attempt = 1; $attempt <= $maxAttempts; $attempt++) {
        try {
            if (!$pdo->beginTransaction()) {
                throw new RuntimeException('Password reset transaction could not start.');
            }

            $result = $operation();

            if (!$pdo->commit()) {
                throw new RuntimeException('Password reset transaction could not commit.');
            }

            return $result;
        } catch (Throwable $exception) {
            if ($pdo->inTransaction()) {
                $pdo->rollBack();
            }

            if ($attempt < $maxAttempts && isRetryableTransactionFailure($exception)) {
                backoffBeforeTransactionRetry($attempt);
                continue;
            }

            throw $exception;
        }
    }

    throw new RuntimeException('Password reset transaction failed.');
}

/**
 * Preserve the existing password-reset helper name while sharing the same
 * bounded transaction/retry behavior with staff password changes.
 */
function runPasswordResetTransaction(PDO $pdo, callable $operation)
{
    return runAuthenticationRevisionTransaction($pdo, $operation);
}

/**
 * Issue a reset token for a known Staff_ID through a controlled internal path.
 *
 * The returned raw token is intended only for a future approved delivery
 * adapter. No current HTTP endpoint calls this function, and the token is
 * never persisted or logged.
 *
 * @return string|null Raw token for an approved internal delivery caller.
 */
function issuePasswordResetToken(PDO $pdo, $staffId, $requestedTtl = null)
{
    $staffId = validatePasswordResetStaffId($staffId);
    $ttlSeconds = getPasswordResetTokenTtlSeconds($requestedTtl);
    $rawToken = bin2hex(random_bytes(32));
    $tokenHash = hash('sha256', $rawToken);

    $issued = runPasswordResetTransaction($pdo, function () use ($pdo, $staffId, $tokenHash, $ttlSeconds) {
        $lockedStaffId = lockStaffForPasswordReset($pdo, $staffId);

        if ($lockedStaffId === false) {
            return false;
        }

        revokeActivePasswordResetTokens($pdo, $lockedStaffId);
        insertPasswordResetToken($pdo, $lockedStaffId, $tokenHash, $ttlSeconds);

        return true;
    });

    return $issued === true ? $rawToken : null;
}

/**
 * Resolve a validly shaped reset identifier and issue through the same
 * atomic lifecycle. Public callers must always use a generic response.
 *
 * @return string|null Raw token for an approved internal delivery caller.
 */
function issuePasswordResetTokenForIdentifier(PDO $pdo, $identifier, $requestedTtl = null)
{
    if (!is_string($identifier) || trim($identifier) === '') {
        return null;
    }

    $staffId = findStaffIdForPasswordReset($pdo, trim($identifier));

    if ($staffId === false) {
        return null;
    }

    return issuePasswordResetToken($pdo, $staffId, $requestedTtl);
}

/**
 * Consume a reset token and update the Staff password atomically.
 *
 * Invalid, expired, used, revoked, and unknown tokens all return false. A
 * database failure is thrown for the API boundary to convert to a generic 500.
 */
function resetPasswordWithToken(PDO $pdo, $rawToken, $newPassword)
{
    if (!validatePasswordResetRawToken($rawToken)
        || !isValidPasswordResetPassword($newPassword)) {
        return false;
    }

    $tokenHash = hash('sha256', $rawToken);
    $tokenOwner = findPasswordResetTokenOwner($pdo, $tokenHash);

    if ($tokenOwner === false) {
        return false;
    }

    $ownerStaffId = (string) ($tokenOwner['Staff_ID'] ?? '');
    $ownerResetId = (int) ($tokenOwner['Reset_ID'] ?? 0);

    if ($ownerStaffId === '' || $ownerResetId < 1) {
        return false;
    }

    return runPasswordResetTransaction($pdo, function () use (
        $pdo,
        $tokenHash,
        $newPassword,
        $ownerStaffId,
        $ownerResetId
    ) {
        $lockedStaffId = lockStaffForPasswordReset($pdo, $ownerStaffId);

        if ($lockedStaffId === false) {
            return false;
        }

        $token = findUsablePasswordResetTokenForUpdate($pdo, $tokenHash);

        if ($token === false
            || (string) ($token['Staff_ID'] ?? '') !== $lockedStaffId
            || (int) ($token['Reset_ID'] ?? 0) !== $ownerResetId) {
            return false;
        }

        $passwordHash = password_hash($newPassword, PASSWORD_DEFAULT);
        if (!is_string($passwordHash)) {
            throw new RuntimeException('Password hashing failed.');
        }

        updateStaffPasswordAndIncrementAuthRevision($pdo, $lockedStaffId, $passwordHash);

        if (markPasswordResetTokenUsed($pdo, $ownerResetId) !== 1) {
            throw new RuntimeException('Password reset token consumption failed.');
        }

        revokeOtherActivePasswordResetTokens($pdo, $lockedStaffId, $ownerResetId);

        return true;
    });
}

/**
 * Delete expired reset records through the same bounded transaction helper.
 */
function cleanupExpiredPasswordResetTokens(PDO $pdo)
{
    return runPasswordResetTransaction($pdo, function () use ($pdo) {
        return deleteExpiredPasswordResetTokens($pdo);
    });
}
